apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trace-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - persistent-volume.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

# 환경별 오버레이
# kubectl apply -k overlays/production/
# kubectl apply -k overlays/development/

commonLabels:
  app: trace
  version: v1

images:
  - name: trace-app
    newName: your-registry/trace-app
    newTag: v1.0.0

configMapGenerator:
  - name: trace-config
    behavior: merge
    literals:
      - ENVIRONMENT=production

secretGenerator:
  - name: trace-secret
    behavior: merge
    literals:
      - DB_PASSWORD=production_password
      - JWT_SECRET=production_jwt_secret
      - API_KEY=production_api_key
